@startuml
 title UML Diagram of Chess Website
 !include ../src/main/java/net/richardmarston/engine/EngineIO.java
 !include ../src/main/java/net/richardmarston/engine/ChessEngine.java
 !include ../src/main/java/net/richardmarston/engine/StatusMessage.java
 !include ../src/main/java/net/richardmarston/controller/ChessController.java
 !include ../src/main/java/net/richardmarston/model/Board.java
 !include ../src/main/java/net/richardmarston/model/Move.java
 !include ../src/main/java/net/richardmarston/view/Messages.java
@enduml

